### ISSUE TITLE
Release '9-2020-q2' is not usable

### ISSUE THREAD

**Issue by rleh** [fiam/arm-none-eabi-gcc#5]
For some reason it does not seem to exist, but [it should](https://github.com/fiam/arm-none-eabi-gcc/blob/master/src/gcc.ts#L2).

With release key `9-2020-q2` (https://github.com/rleh/modm/runs/1074306584):
```
##[error]gcc version 9-2020-q2 is not supported
```

WIth release key `9-2020-q2-update` (https://github.com/rleh/modm/runs/1074311049):
```
##[error]invalid version 9-2020-q2-update. Available: 9-2019-q4,8-2019-q3,8-2018-q4,7-2018-q2,7-2017-q4,6-2017-q2,6-2017-q1,6-2016-q4,5-2016-q3,5-2016-q2,5-2016-q1,5-2015-q4,4.9-2015-q3,4.9-2015-q2,4.9-2015-q1,4.9-2014-q4,4.8-2014-q3,4.8-2014-q2,4.8-2014-q1,4.7-2014-q2,4.8-2013-q4,4.7-2013-q3,4.7-2013-q2,4.7-2013-q1,4.7-2012-q4
```

Any ideas?

**Comment by fiam** [comment]
@rleh I've recently fixed this by creating a `v1` branch. I was expecting GH actions to interpret `@v1` as a semantic version and automatically pulling tags like `v1.0.x`, but that's not the case.

I've just setup a test repo with an action using the `9-2020-q2` SDK and it correctly installs it.

![image](https://user-images.githubusercontent.com/41529/99440460-8a35e180-290e-11eb-90dc-ea71ade4764b.png)

**Comment by rleh** [comment]
Thanks!
