### ISSUE TITLE
Error: The `add-path` command is disabled.

### ISSUE THREAD

**Issue by DennisNurtio** [fiam/arm-none-eabi-gcc#9]
Hello, 

I currently receive this error:
```
Run fiam/arm-none-eabi-gcc@v1
  with:
    release: 9-2019-q4
downloading gcc 9-2019-q4 from https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
(node:2827) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
extracting to /tmp/tmp-2827ccPMC1L3GzAw/gcc-9-2019-q4
Error: Unable to process command '::add-path::/tmp/tmp-2827ccPMC1L3GzAw/gcc-9-2019-q4/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

The `add-path` command was disabled yesterday by GitHub, see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ .

**Comment by DennisNurtio** [comment]
It does still work with the mentioned workaround:

```
     - name: Setup arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          release: '9-2019-q4'
```

**Comment by fiam** [comment]
Thanks for the heads up @DennisNurtio. I've just updated the dependencies and tagged `v1.0.3`, which should fix the problem.

**Comment by stsdc** [comment]
Hope this will be released soon. :pleading_face:

**Comment by fiam** [comment]
@stsdc @DennisNurtio I've just set up a `v1` branch, which should make the fix available without having to reference the specific tag. Please, let me know if it's now working for you.

**Comment by stsdc** [comment]
It's working! Thanks a lot! :heart:

**Comment by DennisNurtio** [comment]
@fiam Thanks for your quick help!

I reverted the workaround and my build works again without it. So the issue is fixed, and indeed applied without having to specify a specific tag.

**Comment by fiam** [comment]
Thanks to you guys! Closing it, since it seems fixed now.
